name = "eduquest-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Environment variables (set these in Cloudflare dashboard or via wrangler secret)
[vars]
ENVIRONMENT = "development"
SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_ANON_KEY = "your-anon-key"

# KV namespaces for caching (optional)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# R2 buckets for file storage (optional)
# [[r2_buckets]]
# binding = "FILES"
# bucket_name = "eduquest-files"

[build]
command = ""

[env.production]
name = "eduquest-api-prod"
vars = { ENVIRONMENT = "production" }

